# AXE DE ACO FIGHTER resources generated by tools/image-tools/build_axe_de_aco_fighter_assets.py
IMAGE img_stage_bg_b "bgs/stage_bg_b.png" BEST
IMAGE img_stage_bg_a "bgs/stage_bg_a.png" BEST

SPRITE spr_marina_idle "sprites/marina/idle.png" 10 11 FAST 6
SPRITE spr_marina_walk_forward "sprites/marina/walk_forward.png" 10 11 FAST 5
SPRITE spr_marina_walk_back "sprites/marina/walk_back.png" 10 11 FAST 5
SPRITE spr_marina_dash "sprites/marina/dash.png" 10 11 FAST 3
SPRITE spr_marina_crouch "sprites/marina/crouch.png" 10 11 FAST 7
SPRITE spr_marina_hop "sprites/marina/hop.png" 10 11 FAST 5
SPRITE spr_marina_guard "sprites/marina/guard.png" 10 11 FAST 6
SPRITE spr_marina_light_attack "sprites/marina/light_attack.png" 10 11 FAST 4
SPRITE spr_marina_medium_attack "sprites/marina/medium_attack.png" 10 11 FAST 4
SPRITE spr_marina_sweep_or_throw "sprites/marina/sweep_or_throw.png" 10 11 FAST 4
SPRITE spr_marina_hurt "sprites/marina/hurt.png" 10 11 FAST 5
SPRITE spr_marina_knockdown "sprites/marina/knockdown.png" 10 11 FAST 7
SPRITE spr_marina_getup "sprites/marina/getup.png" 10 11 FAST 6

SPRITE spr_bento_idle "sprites/bento/idle.png" 11 11 FAST 6
SPRITE spr_bento_walk_forward "sprites/bento/walk_forward.png" 11 11 FAST 5
SPRITE spr_bento_walk_back "sprites/bento/walk_back.png" 11 11 FAST 5
SPRITE spr_bento_dash "sprites/bento/dash.png" 11 11 FAST 3
SPRITE spr_bento_crouch "sprites/bento/crouch.png" 11 11 FAST 7
SPRITE spr_bento_hop "sprites/bento/hop.png" 11 11 FAST 5
SPRITE spr_bento_guard "sprites/bento/guard.png" 11 11 FAST 6
SPRITE spr_bento_light_attack "sprites/bento/light_attack.png" 11 11 FAST 4
SPRITE spr_bento_medium_attack "sprites/bento/medium_attack.png" 11 11 FAST 4
SPRITE spr_bento_sweep_or_throw "sprites/bento/sweep_or_throw.png" 11 11 FAST 4
SPRITE spr_bento_hurt "sprites/bento/hurt.png" 11 11 FAST 5
SPRITE spr_bento_knockdown "sprites/bento/knockdown.png" 11 11 FAST 7
SPRITE spr_bento_getup "sprites/bento/getup.png" 11 11 FAST 6

SPRITE spr_hit_spark "sprites/fx/hit_spark.png" 4 4 FAST 3
SPRITE spr_dust "sprites/fx/dust.png" 3 2 FAST 4
