#!/usr/bin/env python3
"""Promote measured Scene 1 panel assets for BENCHMARK_VISUAL_LAB_V3.

This builder is the canonical promotion step after the measurement-only gate:
- reads the measured panel manifest
- exports indexed SGDK-ready panel PNGs into res/
- writes a machine-readable asset manifest
- writes resources.res deterministically

It does not touch runtime code. Runtime integration remains a separate gate.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from build_bvl_showcase_assets import build_shared_opaque_palette, ensure_dir, save_indexed_bg
from build_bvl_v2_scene1_assets import compose_backgrounds


SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE_ROOT = SCRIPT_DIR.parent.parent
DEFAULT_PROJECT_ROOT = WORKSPACE_ROOT / "SGDK_projects" / "BENCHMARK_VISUAL_LAB_V3"
DEFAULT_FOREST_ROOT = WORKSPACE_ROOT / "SGDK_projects" / "data" / "Forest parallax - Parallax (Forest) vertical"
DEFAULT_MEASURED_MANIFEST = (
    DEFAULT_PROJECT_ROOT
    / "doc"
    / "source_cases"
    / "scene_multiplane_showcase_v3"
    / "reports"
    / "scene1_panel_manifest_measured.json"
)
DEFAULT_PLAN_PATH = DEFAULT_PROJECT_ROOT / "doc" / "scene1-panel-manifest-plan.json"
DEFAULT_RES_ROOT = DEFAULT_PROJECT_ROOT / "res" / "bgs" / "scene1"
DEFAULT_CASE_REPORT = (
    DEFAULT_PROJECT_ROOT
    / "doc"
    / "source_cases"
    / "scene_multiplane_showcase_v3"
    / "reports"
    / "scene1_panel_assets_manifest.json"
)
DEFAULT_RES_FILE = DEFAULT_PROJECT_ROOT / "res" / "resources.res"
DEFAULT_LOG_OUT = DEFAULT_PROJECT_ROOT / "out" / "logs" / "scene1_asset_promotion_report.json"

FINAL_RELEASE_SELECTION: dict[tuple[str, str], tuple[int, ...]] = {
    ("BG_B", "sky"): (0, 1, 2, 3, 4),
    ("BG_B", "forest_ground"): (0, 1, 2),
    ("BG_A", "forest_ground"): (1, 2, 3, 4),
}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def plane_key_from_name(plane_name: str) -> str:
    return plane_name.lower()


def build_panel_resource_name(plane_name: str, band_name: str, panel_index: int) -> str:
    return f"scene1_{plane_name.lower()}_{band_name}_p{panel_index:02d}"


def build_panel_path(output_root: Path, plane_name: str, band_name: str, panel_index: int) -> Path:
    return output_root / f"{build_panel_resource_name(plane_name, band_name, panel_index)}.png"


def build_resources_res(entries: list[dict[str, Any]]) -> str:
    lines = [
        "// Auto-generated by tools/image-tools/build_bvl_v3_scene1_assets.py",
        "// Canonical final-release panel assets for BENCHMARK_VISUAL_LAB_V3.",
        "",
    ]

    for plane_name in ("BG_B", "BG_A"):
        plane_entries = [entry for entry in entries if entry["plane"] == plane_name]
        if not plane_entries:
            continue
        lines.append(f"// {plane_name} panel cache sources")
        for entry in plane_entries:
            rel_path = entry["output_rel"].replace("\\", "/")
            lines.append(f'IMAGE {entry["resource_name"]} "{rel_path}" NONE ALL 0')
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def compute_palette_digest(palette_image) -> str:
    palette = palette_image.getpalette() or []
    return hashlib.sha1(bytes(palette)).hexdigest()


def measure_unique_tiles_rgba(image) -> int:
    width, height = image.size
    tiles_x = width // 8
    tiles_y = height // 8
    unique_tiles: set[bytes] = set()

    for tile_y in range(tiles_y):
        for tile_x in range(tiles_x):
            tile = image.crop((tile_x * 8, tile_y * 8, (tile_x + 1) * 8, (tile_y + 1) * 8))
            unique_tiles.add(tile.tobytes())

    return len(unique_tiles)


def export_panel_assets(
    measured_manifest: dict[str, Any],
    bg_b,
    bg_a,
    output_root: Path,
    project_root: Path,
    res_root: Path,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    ensure_dir(output_root)
    planes = {
        "BG_B": bg_b,
        "BG_A": bg_a,
    }

    asset_entries: list[dict[str, Any]] = []
    resident_tiles_estimate = 0
    max_swap_tiles = 0
    max_palette_slots = 0
    ownership = {
        "BG_B": "ceu_lua_montanha_nuvens_lentas",
        "BG_A": "floresta_proxima_curada_sem_faixas_estruturais_vazias",
        "WINDOW": "hud_tecnico_fixo",
        "SPRITES": "reservado_para_actor_minimo_ou_fx_essencial",
    }

    for candidate in measured_manifest["panel_candidates_measured"]:
        plane_name = candidate["plane"]
        band_name = candidate["band"]
        selected_panels = FINAL_RELEASE_SELECTION.get((plane_name, band_name))
        if not selected_panels:
            continue
        band_image = planes[plane_name]
        band_y0, band_y1 = candidate["source_y_px"]
        band_crop = band_image.crop((0, band_y0, band_image.width, band_y1)).convert("RGBA")
        panel_payloads: list[dict[str, Any]] = []
        selected_tile_sum = 0
        selected_palette_slots = 0

        for panel in candidate["panels"]:
            panel_index = int(panel["index"])
            if panel_index not in selected_panels:
                continue
            origin_x = int(panel["origin_px"][0])
            panel_width = int(panel["size_px"][0])
            panel_height = int(panel["size_px"][1])
            crop_top = 0
            if (plane_name == "BG_A") and (band_name == "forest_ground"):
                crop_top = max(0, panel_height - 96)
            panel_image = band_crop.crop((origin_x, crop_top, origin_x + panel_width, panel_height)).convert("RGBA")
            unique_tiles_measured = measure_unique_tiles_rgba(panel_image)
            selected_tile_sum += unique_tiles_measured
            selected_palette_slots = max(selected_palette_slots, int(panel["palette_stats"]["palette_slots_required"]))
            panel_payloads.append(
                {
                    "panel": panel,
                    "image": panel_image,
                    "crop_top": crop_top,
                    "unique_tiles_measured": unique_tiles_measured,
                }
            )

        if not panel_payloads:
            continue

        resident_tiles_estimate += selected_tile_sum
        max_palette_slots = max(max_palette_slots, selected_palette_slots)

        shared_palette = build_shared_opaque_palette(
            [payload["image"] for payload in panel_payloads],
            colors=16,
        )
        shared_palette_digest = compute_palette_digest(shared_palette)

        for payload in panel_payloads:
            panel = payload["panel"]
            panel_image = payload["image"]
            crop_top = int(payload["crop_top"])
            resource_name = build_panel_resource_name(plane_name, band_name, int(panel["index"]))
            output_path = build_panel_path(output_root, plane_name, band_name, int(panel["index"]))
            save_indexed_bg(
                panel_image,
                output_path,
                colors=16,
                palette_image=shared_palette,
            )

            unique_tiles = int(payload["unique_tiles_measured"])
            max_swap_tiles = max(max_swap_tiles, unique_tiles)
            asset_entries.append(
                {
                    "resource_name": resource_name,
                    "plane": plane_name,
                    "plane_key": plane_key_from_name(plane_name),
                    "band": band_name,
                    "panel_index": int(panel["index"]),
                    "origin_px": panel["origin_px"],
                    "size_px": [int(panel_image.width), int(panel_image.height)],
                    "draw_origin_tiles": [int(panel["origin_px"][0]) // 8, crop_top // 8],
                    "source_crop_y_px": [crop_top, panel_height],
                    "unique_tiles_measured": unique_tiles,
                    "tile_budget_max": int(panel["tile_budget_max"]),
                    "tile_budget_ok": bool(panel["tile_budget_ok"]),
                    "palette_slots_required": int(panel["palette_stats"]["palette_slots_required"]),
                    "transparent_required": bool(panel["palette_stats"]["transparent_required"]),
                    "role": candidate["role"],
                    "resident_slots_target": int(candidate["resident_slots_target"]),
                    "rom_group": candidate["rom_vram_target"]["rom_group"],
                    "vram_policy": candidate["rom_vram_target"]["vram_policy"],
                    "seams_primary": candidate["seams_fallback"]["primary"],
                    "seams_fallback": candidate["seams_fallback"]["fallback"],
                    "planned_palette_id": candidate["palette_plan"]["planned_palette_id"],
                    "palette_strategy": "shared_candidate_palette",
                    "shared_palette_digest": shared_palette_digest,
                    "release_selection": "final_release",
                    "output_abs": str(output_path),
                    "output_project_rel": str(output_path.relative_to(project_root)),
                    "output_rel": str(output_path.relative_to(res_root)),
                }
            )

    budget_summary = {
        "resident_tiles_estimate": resident_tiles_estimate,
        "resident_tiles_policy": "sum_of_candidate_maxima_one_active_panel_per_band",
        "load_time_dma_tiles_estimate": resident_tiles_estimate,
        "per_frame_dma_tiles_peak_estimate": max_swap_tiles,
        "per_frame_dma_policy": "one_panel_swap_peak_placeholder_until_runtime_measurement",
        "max_palette_slots_required": max_palette_slots,
        "asset_count": len(asset_entries),
        "ownership": ownership,
    }
    return asset_entries, budget_summary


def build_asset_manifest(
    project_root: Path,
    forest_root: Path,
    measured_manifest: dict[str, Any],
    plan: dict[str, Any],
    resource_entries: list[dict[str, Any]],
    budget_summary: dict[str, Any],
    resources_res_path: Path,
) -> dict[str, Any]:
    return {
        "schema_version": "1.0.0",
        "project": measured_manifest["project"],
        "scene_id": measured_manifest["scene_id"],
        "status": "assets_promoted",
        "promotion_state": "implementado",
        "source_pack": {
            "forest_root": str(forest_root),
        },
        "builder_route": {
            "decision": "adapt_existing_builder",
            "builder_script": "tools/image-tools/build_bvl_v3_scene1_assets.py",
            "reused_principles": [
                "compose_backgrounds from build_bvl_v2_scene1_assets.py",
                "save_indexed_bg from build_bvl_showcase_assets.py",
                "measured manifest from build_bvl_v3_scene1_manifest_gate.py",
                "shared opaque palette per panel candidate group",
                "final-release asset selection removes structural BG_A bands flagged as rework",
            ],
        },
        "visible_window": measured_manifest["visible_window"],
        "motion_path": measured_manifest["motion_path"],
        "source_extent_checks": measured_manifest["source_extent_checks"],
        "panel_candidates_measured": measured_manifest["panel_candidates_measured"],
        "overlay_and_reserved_palettes": plan["manifest_plan"]["overlay_and_reserved_palettes"],
        "asset_outputs": {
            "resources_res": str(resources_res_path.relative_to(project_root)),
            "panel_root": str(DEFAULT_RES_ROOT.relative_to(project_root)),
        },
        "resource_entries": resource_entries,
        "budget_summary": budget_summary,
        "final_release_selection": {
            f"{plane}:{band}": list(indices)
            for (plane, band), indices in FINAL_RELEASE_SELECTION.items()
        },
    }


def build_report(
    asset_manifest_path: Path,
    resources_res_path: Path,
    asset_manifest: dict[str, Any],
) -> dict[str, Any]:
    summary = asset_manifest["budget_summary"]
    return {
        "scene_id": asset_manifest["scene_id"],
        "status": "ok",
        "promotion_kind": "scene1_panel_assets",
        "asset_manifest_path": str(asset_manifest_path),
        "resources_res_path": str(resources_res_path),
        "asset_count": int(summary["asset_count"]),
        "resident_tiles_estimate": int(summary["resident_tiles_estimate"]),
        "load_time_dma_tiles_estimate": int(summary["load_time_dma_tiles_estimate"]),
        "per_frame_dma_tiles_peak_estimate": int(summary["per_frame_dma_tiles_peak_estimate"]),
        "max_palette_slots_required": int(summary["max_palette_slots_required"]),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Promote measured Scene 1 panels for BENCHMARK_VISUAL_LAB_V3.")
    parser.add_argument("--project-root", type=Path, default=DEFAULT_PROJECT_ROOT)
    parser.add_argument("--forest-root", type=Path, default=DEFAULT_FOREST_ROOT)
    parser.add_argument("--measured-manifest", type=Path, default=DEFAULT_MEASURED_MANIFEST)
    parser.add_argument("--plan", type=Path, default=DEFAULT_PLAN_PATH)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_RES_ROOT)
    parser.add_argument("--asset-manifest-out", type=Path, default=DEFAULT_CASE_REPORT)
    parser.add_argument("--resources-res", type=Path, default=DEFAULT_RES_FILE)
    parser.add_argument("--log-out", type=Path, default=DEFAULT_LOG_OUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    project_root = args.project_root.resolve()
    forest_root = args.forest_root.resolve()
    measured_manifest_path = args.measured_manifest.resolve()
    plan_path = args.plan.resolve()
    output_root = args.output_root.resolve()
    asset_manifest_out = args.asset_manifest_out.resolve()
    resources_res_path = args.resources_res.resolve()
    log_out = args.log_out.resolve()
    res_root = (project_root / "res").resolve()

    measured_manifest = load_json(measured_manifest_path)
    plan = load_json(plan_path)
    bg_b, bg_a = compose_backgrounds(forest_root)

    resource_entries, budget_summary = export_panel_assets(
        measured_manifest=measured_manifest,
        bg_b=bg_b,
        bg_a=bg_a,
        output_root=output_root,
        project_root=project_root,
        res_root=res_root,
    )
    asset_manifest = build_asset_manifest(
        project_root=project_root,
        forest_root=forest_root,
        measured_manifest=measured_manifest,
        plan=plan,
        resource_entries=resource_entries,
        budget_summary=budget_summary,
        resources_res_path=resources_res_path,
    )
    report = build_report(
        asset_manifest_path=asset_manifest_out,
        resources_res_path=resources_res_path,
        asset_manifest=asset_manifest,
    )

    ensure_dir(asset_manifest_out.parent)
    ensure_dir(resources_res_path.parent)
    ensure_dir(log_out.parent)
    asset_manifest_out.write_text(json.dumps(asset_manifest, indent=2), encoding="utf-8")
    resources_res_path.write_text(build_resources_res(resource_entries), encoding="utf-8")
    log_out.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"OK BENCHMARK_VISUAL_LAB_V3 scene1 assets promoted at {project_root}.")


if __name__ == "__main__":
    main()
