SPRITE spr_main_menu    "sprite/spr_main_menu.png"    18  8 FAST 6
SPRITE spr_spaceship    "sprite/spr_spaceship.png"     5  4 FAST 3
SPRITE spr_spaceship2   "sprite/spr_spaceship2.png"    5  4 FAST 3
SPRITE spr_bullet_red   "sprite/spr_bullet_red.png"    1  1 NONE 2
SPRITE spr_bullet_blue  "sprite/spr_bullet_blue.png"   1  1 NONE 2
SPRITE spr_bullet_super "sprite/spr_bullet_super.png"  4  2 NONE 2
SPRITE spr_super        "sprite/spr_super.png"         2  2 FAST 2
SPRITE spr_itens        "sprite/spr_itens.png"         2  2 FAST 2
SPRITE spr_numbers      "sprite/spr_numbers.png"       1  1 FAST 0
SPRITE spr_speed_bar    "sprite/spr_speed_bar.png"     3  1 FAST 4
SPRITE spr_super_bar    "sprite/spr_super_bar.png"     5  1 FAST 4
SPRITE spr_bomb_cont    "sprite/spr_bomb_cont.png"     6  1 FAST 12
SPRITE spr_item_box     "sprite/spr_item_box.png"      2  2 FAST 6
SPRITE spr_explosion    "sprite/spr_explosion.png"     5  5 FAST 4
SPRITE spr_bomb         "sprite/spr_bomb.png"         12 12 FAST 6
SPRITE spr_enemy01      "sprite/spr_enemy01.png"       2  2 FAST 4
SPRITE spr_enemy02      "sprite/spr_enemy02.png"       4  4 FAST 5
SPRITE spr_enemy03      "sprite/spr_enemy03.png"       5  6 FAST 4
SPRITE spr_enemy04      "sprite/spr_enemy04.png"       3  3 FAST 7