IMAGE urban_default_bg_b "gfx/sky_bg_b.png" BEST
IMAGE urban_default_bg_a "gfx/city_bg_a_448.png" BEST
IMAGE urban_linefirst_balanced_bg_b "gfx/urban_linefirst_balanced_bg_b.png" BEST
IMAGE urban_linefirst_balanced_bg_a "gfx/urban_linefirst_balanced_bg_a.png" BEST
IMAGE urban_linefirst_cohesive_bg_b "gfx/urban_linefirst_cohesive_bg_b.png" BEST
IMAGE urban_linefirst_cohesive_bg_a "gfx/urban_linefirst_cohesive_bg_a.png" BEST
IMAGE mission1_shared_bg_b "gfx/mission1_skylift_bg_b.png" BEST
IMAGE mission1_flat_strict15_bg_a "gfx/mission1_flat_strict15.png" BEST
IMAGE mission1_flat_snap700_bg_a "gfx/mission1_flat_snap_700.png" BEST
IMAGE mission1_skylift_bg_a "gfx/mission1_skylift_bg_a.png" BEST
