#!/usr/bin/env python3
"""Adversarial semantic fixtures for the two-layer TAINA topology meter."""
from __future__ import annotations

import copy
import importlib.util
import json
import tempfile
from pathlib import Path


HERE = Path(__file__).resolve().parent
METER_PATH = HERE / "repair_material_topology_meter_v03.py"
LAB = HERE.parent
V05_DIR = LAB / "localized_native_cleanup" / "hybrid_cleanup_primary_im_lanczos3_rework_v05"
IMAGE = V05_DIR / "hybrid_cleanup_primary_im_lanczos3_rework_v05.png"
ANNOTATION = V05_DIR / "material_owner_shade_annotation_v01.json"

spec = importlib.util.spec_from_file_location("meter_v03", METER_PATH)
meter = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(meter)


def load() -> dict:
    return json.loads(ANNOTATION.read_text(encoding="utf-8"))


def set_cell(rows: list[str], x: int, y: int, code: str) -> None:
    row = list(rows[y]); row[x] = code; rows[y] = "".join(row)


def eval_mutation(obj: dict, name: str) -> dict:
    with tempfile.TemporaryDirectory(prefix="taina_topology_fixture_") as td:
        path = Path(td) / f"{name}.json"
        path.write_text(json.dumps(obj), encoding="utf-8")
        return meter.evaluate(IMAGE, path)


def main() -> None:
    base = load()
    results = {}

    # 1. A visible unassigned cell must not silently become skin.
    obj = copy.deepcopy(base); set_cell(obj["material_owner_rows"], 27, 26, "?")
    r = eval_mutation(obj, "fallback_residual"); results["fallback_residual_for_skin"] = {"passed": r["unassigned_visible_pixel"] == [{"x": 27, "y": 26}], "observed": r["unassigned_visible_pixel"][:3]}

    # 2. A hair pixel relabeled as skin must fail an independent semantic anchor.
    obj = copy.deepcopy(base); set_cell(obj["material_owner_rows"], 20, 4, "K")
    r = eval_mutation(obj, "hair_as_skin"); results["hair_as_skin"] = {"passed": bool(r["ownership_anchor_errors"]), "observed": r["ownership_anchor_errors"]}

    # 3. A boundary name with the wrong expected pair must fail, even if the
    # coordinates remain different labels.
    obj = copy.deepcopy(base); obj["boundary_contract"]["hair_skin_face"]["expected_owner_a"] = "orange_top"; obj["boundary_contract"]["hair_skin_face"]["expected_owner_b"] = "skin"
    r = eval_mutation(obj, "wrong_boundary_pair"); results["boundary_name_wrong_pair"] = {"passed": not r["boundaries"]["segments"]["hair_skin_face"]["status"], "observed": r["boundaries"]["segments"]["hair_skin_face"]}

    # 4. Shared outline is coordinate-authorized, not a free shade label.
    obj = copy.deepcopy(base); set_cell(obj["shade_role_rows"], 0, 0, "O")
    r = eval_mutation(obj, "outline_unauthorized"); results["outline_unauthorized_coordinate"] = {"passed": bool(r["shared_role_contract_errors"]), "observed": r["shared_role_contract_errors"][:2]}

    # 5. Deep shared shadow outside its explicit role contract must fail.
    obj = copy.deepcopy(base); set_cell(obj["shade_role_rows"], 27, 26, "D")
    r = eval_mutation(obj, "deep_shadow_unauthorized"); results["deep_shadow_outside_contract"] = {"passed": bool(r["shared_role_contract_errors"]), "observed": r["shared_role_contract_errors"][:2]}

    # 6. Empty wraps/sash segments are vacuous truth, not a passing boundary.
    obj = copy.deepcopy(base); obj["boundary_contract"]["sash_trousers"]["segments"] = []
    r = eval_mutation(obj, "vacuous_sash"); results["vacuous_wrap_sash_boundary"] = {"passed": not r["boundaries"]["contract_complete"] and not r["boundaries"]["status"], "observed": r["boundaries"]}

    # 7. One correct foot pixel does not prove both ankle boundaries.
    obj = copy.deepcopy(base)
    for x, y in [(15, 69), (16, 69), (40, 69), (41, 69)]: set_cell(obj["material_owner_rows"], x, y, ".")
    set_cell(obj["material_owner_rows"], 15, 69, "K")
    r = eval_mutation(obj, "one_foot_pixel"); results["one_correct_foot_pixel"] = {"passed": not r["boundaries"]["segments"]["skin_trousers_left_ankle"]["status"] or not r["boundaries"]["segments"]["skin_trousers_right_ankle"]["status"], "observed": {"left": r["boundaries"]["segments"]["skin_trousers_left_ankle"], "right": r["boundaries"]["segments"]["skin_trousers_right_ankle"]}}

    # 8. Expanding one index globally cannot buy zero leakage; the shade role
    # remains base and the owner ramp remains explicit.
    obj = copy.deepcopy(base); r0 = eval_mutation(obj, "global_index_control")
    r = r0
    results["global_index_expansion_not_authorized"] = {"passed": r["material_palette_leakage"] > 0, "observed": {"leakage": r["material_palette_leakage"], "index_2_global_shadow_reuse": r["shared_family_valid"]["index_2_global_shadow_reuse"]}}

    # 9. Metadata that says ownership was generated by palette index is itself
    # rejected, even when the rows happen to look complete.
    obj = copy.deepcopy(base); obj["owner_assignment_method"] = "palette_index_lookup"; obj["palette_indices_not_used_for_owner_assignment"] = False; obj["owner_fallback"] = "skin"
    r = eval_mutation(obj, "palette_generated_map"); results["map_generated_from_asset_palette"] = {"passed": bool(r["annotation_provenance_errors"]), "observed": r["annotation_provenance_errors"]}

    accounting = json.loads((V05_DIR / "material_topology_measurement_report.json").read_text(encoding="utf-8"))["patch_accounting"]
    results["no_op_accounting"] = {"passed": accounting == {"patches_attempted": 23, "patches_effective": 18, "patches_noop": 5}, "observed": accounting}
    failed = [name for name, result in results.items() if not result["passed"]]
    report = {"schema_version": "taina_material_topology_adversarial_fixtures.v1", "fixture_count": len(results), "passed": len(results) - len(failed), "failed": len(failed), "results": results, "semantic_assertions_not_counter_only": True}
    out = V05_DIR / "material_topology_fixture_report.json"
    out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"passed": report["passed"], "failed": report["failed"], "report": str(out)}, ensure_ascii=False))
    if failed:
        raise SystemExit("fixture failures: " + ", ".join(failed))


if __name__ == "__main__":
    main()
