// Showdown fixture binaries generated by the root study pipeline.
BIN bin_showdown_tiles "data/showdown/showdown_tiles_4bpp.bin" 2 2 0 NONE FALSE
BIN bin_showdown_maps "data/showdown/showdown_maps_u16.bin" 2 2 0 NONE FALSE
BIN bin_showdown_palettes "data/showdown/showdown_palettes_u16.bin" 2 2 0 NONE FALSE
