<#
.SYNOPSIS
  Prepara a camada consultiva ai-memory sem alterar hooks globais.

.DESCRIPTION
  Esta integracao e project-scoped e conservadora:
  - cria marcadores `.ai-memory.toml` controlados quando ausentes;
  - documenta a politica canonica em `doc/AI_MEMORY_POLICY.md`;
  - nunca executa `install-hooks --apply`, `install-mcp --apply` ou bootstrap;
  - nao substitui memory bank, learning ledger, validators, Graphify ou evidencia.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$RepoRoot = "",

    [Parameter(Mandatory = $false)]
    [string]$ProjectRoot = "",

    [Parameter(Mandatory = $false)]
    [ValidateSet('Audit', 'Prepare')]
    [string]$Mode = 'Prepare',

    [Parameter(Mandatory = $false)]
    [ValidateSet('Host', 'Json')]
    [string]$OutputFormat = 'Host',

    [Parameter(Mandatory = $false)]
    [string]$WorkspaceId = 'sgdk_forge',

    [Parameter(Mandatory = $false)]
    [string]$RootProjectId = 'workspace',

    [Parameter(Mandatory = $false)]
    [string]$ProjectId = '',

    [Parameter(Mandatory = $false)]
    [switch]$SkipRootMarker,

    [Parameter(Mandatory = $false)]
    [switch]$SkipProjectMarker
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$managedMarker = 'SGDK Forge managed ai-memory'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Resolve-ForgedRepoRoot {
    param([string]$ExplicitRoot)
    if (-not [string]::IsNullOrWhiteSpace($ExplicitRoot)) {
        return [System.IO.Path]::GetFullPath($ExplicitRoot)
    }
    $wrapperDirInfo = [System.IO.DirectoryInfo]$PSScriptRoot
    $toolsDirInfo = $wrapperDirInfo.Parent
    $rootDirInfo = $toolsDirInfo.Parent
    return [System.IO.Path]::GetFullPath($rootDirInfo.FullName)
}

function ConvertTo-AiMemoryId {
    param(
        [Parameter(Mandatory = $false)][string]$Value,
        [Parameter(Mandatory = $true)][string]$Fallback
    )

    $raw = if ([string]::IsNullOrWhiteSpace($Value)) { $Fallback } else { $Value }
    $normalized = $raw.Normalize([System.Text.NormalizationForm]::FormD)
    $builder = New-Object System.Text.StringBuilder
    foreach ($ch in $normalized.ToCharArray()) {
        $category = [System.Globalization.CharUnicodeInfo]::GetUnicodeCategory($ch)
        if ($category -ne [System.Globalization.UnicodeCategory]::NonSpacingMark) {
            [void]$builder.Append($ch)
        }
    }

    $asciiish = $builder.ToString().Normalize([System.Text.NormalizationForm]::FormC).ToLowerInvariant()
    $slug = [regex]::Replace($asciiish, '[^a-z0-9._-]+', '_')
    $slug = [regex]::Replace($slug, '_{2,}', '_').Trim('._-')
    if ([string]::IsNullOrWhiteSpace($slug)) {
        $slug = $Fallback
    }
    if ($slug -notmatch '^[a-z0-9]') {
        $slug = "p_$slug"
    }
    $slug = $slug.Trim('._-')
    if ([string]::IsNullOrWhiteSpace($slug)) {
        $slug = $Fallback
    }
    return $slug
}

function New-MarkerContent {
    param(
        [Parameter(Mandatory = $true)][string]$Workspace,
        [Parameter(Mandatory = $true)][string]$Project
    )

    return @"
# SGDK Forge managed ai-memory marker.
# Authority: consultive only. Canonical truth stays in AGENTS.md, memory banks,
# validators, changelog and emulator evidence.
# Generated by tools/sgdk_wrapper/prepare_ai_memory_integration.ps1.
workspace = "$Workspace"
project = "$Project"
"@
}

function New-PolicyContent {
    return @'
# SGDK Forge managed ai-memory policy.

# AI Memory Policy

Status: `consultive_optional_layer`

## Role

`ai-memory` may be used as a project-local, cross-agent memory aid for handoff,
search and operational recall.

It is not a source of truth for SGDK Forge.

## Authority

Authoritative state remains, in order:

- `doc/10-memory-bank.md` inside a project, or `doc/06_AI_MEMORY_BANK.md` for workspace scope;
- GDD/TDD/spec/manifests/changelog;
- validators and reports in `out/logs/`;
- BlastEm evidence tied to the same ROM hash;
- SGDK headers and wrapper contracts.

`ai-memory` retrieval can suggest where to look, but every decision must be
validated by opening the canonical files or evidence it references.

## Controlled Integration

- `.ai-memory.toml` markers are allowed as routing hints.
- Root marker scope is `workspace`; project markers should be created inside
  each project by `adopt_project_methodology.ps1` or
  `prepare_ai_memory_integration.ps1 -ProjectRoot`.
- The wrapper never runs `install-hooks --apply`, `install-mcp --apply`,
  `bootstrap`, `auto-improve`, `pending-writes approve` or any global client
  mutation automatically.
- Auto-improvement must remain pending for human review. For ai-memory configs,
  use `[auto_improve] require_approval = true` and prefer disabling the
  scheduler until the pilot is approved.
- No ai-memory page can promote `documentado` to `implementado`, `buildado`,
  `testado_em_emulador`, `validado_budget`, `MESTRE_*`, `stable`, `release` or
  `ready_for_aaa`.

## First Host Startup

`assert_agent_environment.ps1` calls `prepare_agent_environment.ps1`, which
calls `prepare_ai_memory_integration.ps1`. This prepares local markers and this
policy with minimal output. Missing ai-memory CLI/server is reported as optional
and does not block the SGDK framework.

## Human Setup Boundary

Installing ai-memory itself, wiring MCP/hook clients, configuring bearer tokens
or selecting an LLM provider is a host/user action. Do it from the same
environment that launches the agent, then verify the agent can call
`memory_status` or equivalent.
'@
}

function Get-ManagedFileStatus {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return 'missing'
    }
    $text = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    if ($text -match [regex]::Escape($managedMarker)) {
        return 'present'
    }
    return 'present_external'
}

function Set-ManagedTextFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    if (Test-Path -LiteralPath $Path -PathType Leaf) {
        $existing = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
        if ($existing -notmatch [regex]::Escape($managedMarker)) {
            return 'preserved_external'
        }
        if ($existing -eq $Content) {
            return 'present'
        }
        [System.IO.File]::WriteAllText($Path, $Content, $script:utf8NoBom)
        return 'updated'
    }

    $parent = Split-Path $Path -Parent
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    [System.IO.File]::WriteAllText($Path, $Content, $script:utf8NoBom)
    return 'created'
}

$repo = Resolve-ForgedRepoRoot -ExplicitRoot $RepoRoot
$modeValue = $Mode.ToLowerInvariant()
$workspace = ConvertTo-AiMemoryId -Value $WorkspaceId -Fallback 'sgdk_forge'
$rootProject = ConvertTo-AiMemoryId -Value $RootProjectId -Fallback 'workspace'
$resolvedProjectRoot = ''
$projectMarkerStatus = 'skipped'
$projectMarkerPath = $null
$projectMemoryId = $null

if (-not [string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $resolvedProjectRoot = [System.IO.Path]::GetFullPath($ProjectRoot)
    $projectMarkerPath = Join-Path $resolvedProjectRoot '.ai-memory.toml'
    $leafName = Split-Path $resolvedProjectRoot -Leaf
    $projectMemoryId = ConvertTo-AiMemoryId -Value $ProjectId -Fallback (ConvertTo-AiMemoryId -Value $leafName -Fallback 'project')
}

$rootMarkerPath = Join-Path $repo '.ai-memory.toml'
$policyPath = Join-Path $repo 'doc\AI_MEMORY_POLICY.md'
$reportPath = Join-Path $repo 'out\logs\ai_memory_integration_report.json'

$actions = [ordered]@{
    root_marker_write_status = 'skipped'
    project_marker_write_status = 'skipped'
    policy_write_status = 'skipped'
    report_written = $false
    install_hooks_apply_performed = $false
    install_mcp_apply_performed = $false
    bootstrap_performed = $false
    auto_improve_performed = $false
}

if ($modeValue -eq 'prepare') {
    if (-not $SkipRootMarker) {
        $actions.root_marker_write_status = Set-ManagedTextFile `
            -Path $rootMarkerPath `
            -Content (New-MarkerContent -Workspace $workspace -Project $rootProject)
    }

    $actions.policy_write_status = Set-ManagedTextFile -Path $policyPath -Content (New-PolicyContent)

    if (-not $SkipProjectMarker -and -not [string]::IsNullOrWhiteSpace($resolvedProjectRoot) -and (Test-Path -LiteralPath $resolvedProjectRoot -PathType Container)) {
        $actions.project_marker_write_status = Set-ManagedTextFile `
            -Path $projectMarkerPath `
            -Content (New-MarkerContent -Workspace $workspace -Project $projectMemoryId)
    } elseif (-not [string]::IsNullOrWhiteSpace($resolvedProjectRoot)) {
        $actions.project_marker_write_status = 'project_root_missing'
    }
}

$rootMarkerStatus = if ($SkipRootMarker) { 'skipped' } else { Get-ManagedFileStatus -Path $rootMarkerPath }
if (-not [string]::IsNullOrWhiteSpace($resolvedProjectRoot) -and -not $SkipProjectMarker) {
    if (Test-Path -LiteralPath $resolvedProjectRoot -PathType Container) {
        $projectMarkerStatus = Get-ManagedFileStatus -Path $projectMarkerPath
    } else {
        $projectMarkerStatus = 'project_root_missing'
    }
}
$policyStatus = Get-ManagedFileStatus -Path $policyPath
$cliCommand = Get-Command ai-memory -ErrorAction SilentlyContinue

$report = [ordered]@{
    schema_version = '1.0.0'
    generated_at_utc = (Get-Date).ToUniversalTime().ToString('o')
    mode = $modeValue
    repo_root = $repo
    project_root = $resolvedProjectRoot
    ready = $true
    policy = [ordered]@{
        authority = 'consultive_only'
        canonical_auto_mutation = $false
        human_approval_required = $true
        evidence_required_for_claims = $true
        closeout_gate = $false
    }
    ai_memory_cli = [ordered]@{
        present = [bool]$cliCommand
        path = if ($cliCommand) { [string]$cliCommand.Source } else { $null }
        server_checked = $false
        optional = $true
    }
    root_marker = [ordered]@{
        path = $rootMarkerPath
        status = $rootMarkerStatus
        workspace = $workspace
        project = $rootProject
    }
    project_marker = [ordered]@{
        path = $projectMarkerPath
        status = $projectMarkerStatus
        workspace = $workspace
        project = $projectMemoryId
    }
    docs = [ordered]@{
        policy_path = $policyPath
        policy_status = $policyStatus
    }
    actions = $actions
    guidance = [ordered]@{
        manual_agent_wiring_required = $true
        recommended_ai_memory_config = '[auto_improve] require_approval = true; [auto_improve.scheduler] enabled = false during pilot'
        forbidden_automatic_commands = @(
            'install-hooks --apply',
            'install-mcp --apply',
            'bootstrap',
            'auto-improve',
            'pending-writes approve'
        )
    }
}

if ($modeValue -eq 'prepare') {
    $reportDir = Split-Path $reportPath -Parent
    if (-not (Test-Path -LiteralPath $reportDir -PathType Container)) {
        New-Item -ItemType Directory -Force -Path $reportDir | Out-Null
    }
    $report | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $reportPath -Encoding UTF8
    $report.actions.report_written = $true
    $report | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $reportPath -Encoding UTF8
}

if ($OutputFormat -eq 'Json') {
    $report | ConvertTo-Json -Depth 8
} else {
    Write-Host ("ai_memory_status=ready mode={0} cli_present={1} root_marker={2} project_marker={3} policy={4}" -f `
        $modeValue,
        ([bool]$cliCommand).ToString().ToLowerInvariant(),
        $rootMarkerStatus,
        $projectMarkerStatus,
        $policyStatus)
    if ($modeValue -eq 'prepare') {
        Write-Host "ai_memory_report=$reportPath"
    }
}

exit 0
