#ifndef PP2_H
#define PP2_H

/* =========================================================================
 * Pequeno Príncipe VER.002 — Master Header
 * Include this single header in every .c file.
 * ========================================================================= */

#include <genesis.h>
#include "constants.h"
#include "types.h"

/* -------------------------------------------------------------------------
 * Resources (generated by ResComp)
 * ------------------------------------------------------------------------- */
#include "../res/resources.h"

/* -------------------------------------------------------------------------
 * Engine (core/engine.c)
 * ------------------------------------------------------------------------- */
extern GameCtx g_ctx;

void Engine_init(void);
void Engine_run(void);
void Engine_requestState(GameStateId next);
void Engine_tick(void);

/* -------------------------------------------------------------------------
 * Input (core/input.c)
 * ------------------------------------------------------------------------- */
void Input_init(void);
void Input_update(void);

/* -------------------------------------------------------------------------
 * VBlank (core/vblank.c)
 * ------------------------------------------------------------------------- */
void VBlank_init(void);
void VBlank_setScrollMode(bool lineScroll, bool colScroll);
void VBlank_enableHInt(u16 line);
void VBlank_disableHInt(void);

/* -------------------------------------------------------------------------
 * Audio (core/audio.c)
 * ------------------------------------------------------------------------- */
void Audio_init(void);
void Audio_playBgm(BgmId id);
void Audio_stopBgm(void);
void Audio_fadeOutBgm(void);
void Audio_playSfx(SfxId id);

/* -------------------------------------------------------------------------
 * Player (game/player.c)
 * ------------------------------------------------------------------------- */
void Player_init(GameCtx *ctx);
void Player_reset(GameCtx *ctx, s16 startX, s16 groundY);
void Player_update(GameCtx *ctx, u16 held);
void Player_render(GameCtx *ctx);
void Player_hide(void);
void Player_updateScarf(GameCtx *ctx);
void Player_renderScarf(GameCtx *ctx);
bool Player_isNear(const GameCtx *ctx, s16 x, s16 y, s16 radius);

/* -------------------------------------------------------------------------
 * Dialogue (game/dialogue.c)
 * ------------------------------------------------------------------------- */
void Dialogue_init(void);
void Dialogue_open(GameCtx *ctx, const char *speaker,
                   const char * const *lines, u16 lineCount);
void Dialogue_close(GameCtx *ctx);
void Dialogue_update(GameCtx *ctx);
void Dialogue_handleInput(GameCtx *ctx, u16 pressed);
void Dialogue_draw(GameCtx *ctx);

/* -------------------------------------------------------------------------
 * Codex (game/codex.c)
 * ------------------------------------------------------------------------- */
void Codex_init(void);
void Codex_unlock(GameCtx *ctx, PlanetId planet);
void Codex_draw(GameCtx *ctx);
void Codex_handleInput(GameCtx *ctx, u16 pressed);

/* -------------------------------------------------------------------------
 * HUD (ui/hud.c)
 * ------------------------------------------------------------------------- */
void Hud_init(void);
void Hud_draw(GameCtx *ctx);
void Hud_setPlanet(PlanetId id);
void Hud_setHint(const char *hint);

/* -------------------------------------------------------------------------
 * Menu (ui/menu.c)
 * ------------------------------------------------------------------------- */
void Menu_drawTitle(GameCtx *ctx);
void Menu_drawIntro(GameCtx *ctx);
void Menu_drawPause(GameCtx *ctx);
void Menu_drawCredits(GameCtx *ctx);
void Menu_handleInput(GameCtx *ctx, u16 pressed);

/* -------------------------------------------------------------------------
 * Effects (ui/effects.c)
 * ------------------------------------------------------------------------- */
void Effects_init(void);
void Effects_update(GameCtx *ctx);
void Effects_screenShake(GameCtx *ctx, u16 amplitude, u16 duration);
void Effects_paletteFlash(GameCtx *ctx, u16 color, u16 duration);
void Effects_fadeIn(GameCtx *ctx, u16 speed);
void Effects_fadeOut(GameCtx *ctx, u16 speed);
void Effects_applyShake(GameCtx *ctx);

/* -------------------------------------------------------------------------
 * Planet scenes (planets/)
 * ------------------------------------------------------------------------- */
const PlanetScene *Planet_getScene(PlanetId id);

/* -------------------------------------------------------------------------
 * Travel scenes (travels/)
 * ------------------------------------------------------------------------- */
const TravelScene *Travel_getScene(TravelId id);
TravelId Travel_fromPlanets(PlanetId from, PlanetId to);

#endif /* PP2_H */
