#ifndef SYSTEMS_STAGE_MAP_H
#define SYSTEMS_STAGE_MAP_H

#include <genesis.h>

/*
 * Stage collision for the FASE 1 slice.
 *
 * The terrain strip generated by data/builders/build_placeholder_art.py is a
 * flat floor at a known height with two gaps. Collision reads the SAME
 * constants the art generator used, so art and collision cannot drift apart
 * silently. When real level data arrives this is replaced by a tilemap query.
 */

/* Top of the terrain strip, in pixels, in plane space. */
#define STAGE_GROUND_TOP 176

/* Kirby's origin is his centre, so his feet rest this far below it. */
#define STAGE_FOOT_OFFSET 14

#define STAGE_PLANE_WIDTH 512

/* MISSAO 2026-08-24: vaos agora vem da tabela da fase ativa (journey.c).
 * Sem install, o comportamento canonical da FASE 1 se mantem (GAPS_S0). */
void STAGE_installGaps(const s16* pairsX0X1, u8 gapCount);

/* Goal da fase: coluna X em plane space que dispara a progressao. */
#define STAGE_GOAL_X 428

/* Returns TRUE when solid ground exists at planeX and writes the y coordinate
 * Kirby's centre should rest at. */
bool STAGE_groundAt(s16 planeX, fix16* outCentreY);

#endif
