// Branding intro assets built by tools/image-tools/build_branding_intro_assets.py.
// Every PNG is indexed, 8px aligned, and limited to a single 16-color palette.
IMAGE img_brand_fx_tiles "branding/brand_fx_tiles.png" BEST
IMAGE img_brand_engine_logo "branding/brand_engine_logo.png" BEST
IMAGE img_brand_author_logo "branding/brand_author_logo.png" BEST
IMAGE img_brand_project_logo "branding/brand_project_logo.png" BEST
IMAGE img_brand_presents_text "branding/brand_presents_text.png" BEST

// Branding intro audio uses SGDK 2.11 WAV resources for the XGM2 PCM path.
WAV brand_bell_forge "audio/branding/bell_forge.wav" XGM2 13300
WAV brand_typewriter_click "audio/branding/typewriter_click.wav" XGM2 6650
WAV brand_bell_terminal "audio/branding/bell_terminal.wav" XGM2 13300
WAV brand_stamp_whoosh "audio/branding/stamp_whoosh.wav" XGM2 13300
WAV brand_reverb_tail "audio/branding/reverb_tail.wav" XGM2 13300

// ---- FASE 1 placeholder art. Generated by
// ---- data/builders/build_placeholder_art.py, already on the RGB333 lattice
// ---- and using the canonical palettes from doc/PALETTES.md.
IMAGE img_ph_sky      "gfx/ph_sky.png"      BEST
IMAGE img_ph_mount    "gfx/ph_mount.png"    BEST
IMAGE img_ph_hills    "gfx/ph_hills.png"    BEST
IMAGE img_ph_terrain  "gfx/ph_terrain.png"  BEST
// v10 runtime review candidate: assisted_native_translation, not final art.
SPRITE spr_ph_kirby   "sprites/review_kirby.png" 4 4 BEST
// Human-approved ELITE idle key pose; isolated runtime review only.
SPRITE spr_native_idle_elite "sprites/native_idle_key_pose_elite_v01.png" 4 4 BEST
// v11 native-edit candidate: review-scene integration only; not promoted art.
SPRITE spr_native_run_contact_v11 "sprites/v11_review/run_contact_v11_candidate.png" 1 1 BEST
SPRITE spr_ph_fg      "sprites/ph_fg.png"    4 2 BEST
SPRITE spr_ph_enemy    "sprites/ph_enemy.png"    2 2 BEST
SPRITE spr_ph_particle "sprites/ph_particle.png" 1 1 BEST
SPRITE spr_ph_branch    "sprites/ph_branch.png"    2 2 BEST
SPRITE spr_ph_boss_face "sprites/ph_boss_face.png" 6 4 BEST
SPRITE spr_ph_apple     "sprites/ph_apple.png"     2 2 BEST
IMAGE  img_ph_trunk     "bgs/ph_trunk.png"         BEST
XGM2 mus_stage_valley "audio/mus_stage_valley.vgm"
WAV  sfx_inhale       "sfx/sfx_inhale.wav"   XGM2
WAV  sfx_swallow      "sfx/sfx_swallow.wav"  XGM2
WAV  sfx_hurt         "sfx/sfx_hurt.wav"     XGM2
IMAGE img_ph_title_hill  "bgs/ph_title_hill.png"  BEST
IMAGE img_ph_title_stars "bgs/ph_title_stars.png" BEST
IMAGE img_ph_title_logo  "gfx/ph_title_logo.png"  BEST
// Fire review candidate; remaining abilities keep their existing consumers.
SPRITE spr_ph_ability_fx "sprites/review_fire_fx.png" 2 2 BEST
SPRITE spr_ph_light "sprites/ph_light.png" 4 4 BEST
