#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define PROJECT_TITLE "CELESTIAL CHASE REVIVE"
#define PROJECT_BUILD_LABEL "RUNTIME SEED 001"
#define PROJECT_REGION_LABEL "NTSC/PAL JUE"

#define PROJECT_READY_SRAM_OFFSET 0x100u
#define PROJECT_SCENE_SRAM_OFFSET 0x108u
#define PROJECT_INPUT_SRAM_OFFSET 0x110u
#define PROJECT_READY_PERIOD_FRAMES 30u

#endif
