<#
.SYNOPSIS
    Common artifact envelope helpers for the AAA agent ecosystem.
.DESCRIPTION
    Provides standardized functions for creating, writing, and validating
    JSON artifacts generated by new tooling scripts. All artifacts share
    the common_artifact.schema.json envelope.
.NOTES
    This module does NOT modify any existing wrapper behavior.
    It is consumed only by new standalone scripts behind feature flags.
#>

Set-StrictMode -Version Latest

# ---------------------------------------------------------------------------
# New-SgdkArtifactEnvelope
# ---------------------------------------------------------------------------
function New-SgdkArtifactEnvelope {
    <#
    .SYNOPSIS
        Creates a new artifact envelope hashtable with mandatory base fields.
    .PARAMETER ToolName
        Name of the generating tool (e.g. "capture_blastem_evidence").
    .PARAMETER ToolVersion
        Semantic version of the generating tool.
    .PARAMETER ProjectRoot
        Absolute path to the project root directory.
    .PARAMETER WorkspaceRoot
        Absolute path to the MegaDrive_DEV workspace root.
        If omitted, attempts auto-discovery via MD_ROOT env var.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ToolName,
        [Parameter(Mandatory)][string]$ToolVersion,
        [Parameter(Mandatory)][string]$ProjectRoot,
        [string]$WorkspaceRoot
    )

    if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
        $WorkspaceRoot = $env:MD_ROOT
        if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
            # Fallback: walk up from script location looking for CLAUDE.md
            $probe = $PSScriptRoot
            for ($i = 0; $i -lt 5; $i++) {
                $probe = Split-Path $probe -Parent
                if (Test-Path (Join-Path $probe 'CLAUDE.md')) {
                    $WorkspaceRoot = $probe
                    break
                }
            }
        }
        if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
            $WorkspaceRoot = 'UNKNOWN'
        }
    }

    return [ordered]@{
        schema_version = '1.0.0'
        generated_at   = (Get-Date).ToUniversalTime().ToString('o')
        tool_name      = $ToolName
        tool_version   = $ToolVersion
        project_root   = $ProjectRoot
        workspace_root = $WorkspaceRoot
        status         = 'ok'
        failure_reason = $null
    }
}

# ---------------------------------------------------------------------------
# Set-SgdkArtifactFailure
# ---------------------------------------------------------------------------
function Set-SgdkArtifactFailure {
    <#
    .SYNOPSIS
        Marks an artifact envelope as failed with a reason.
    .PARAMETER Artifact
        The artifact hashtable (modified in-place).
    .PARAMETER Reason
        Human-readable failure description.
    .PARAMETER Warn
        If set, status becomes "warn" instead of "error".
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Artifact,
        [Parameter(Mandatory)][string]$Reason,
        [switch]$Warn
    )

    $Artifact['status'] = if ($Warn) { 'warn' } else { 'error' }
    $Artifact['failure_reason'] = $Reason
}

# ---------------------------------------------------------------------------
# Write-SgdkJsonArtifact
# ---------------------------------------------------------------------------
function Write-SgdkJsonArtifact {
    <#
    .SYNOPSIS
        Serializes an artifact hashtable to a JSON file with UTF-8 encoding.
    .PARAMETER Data
        The artifact hashtable to serialize.
    .PARAMETER Path
        Absolute path for the output JSON file.
        Parent directory is created automatically if missing.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Data,
        [Parameter(Mandatory)][string]$Path
    )

    $parentDir = Split-Path $Path -Parent
    if (-not (Test-Path -LiteralPath $parentDir)) {
        New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
    }

    $json = $Data | ConvertTo-Json -Depth 20
    [System.IO.File]::WriteAllText($Path, $json, [System.Text.Encoding]::UTF8)
    return $Path
}

# ---------------------------------------------------------------------------
# Test-SgdkRequiredFile
# ---------------------------------------------------------------------------
function Test-SgdkRequiredFile {
    <#
    .SYNOPSIS
        Checks whether a required file exists and is non-empty.
    .PARAMETER FilePath
        Absolute path to check.
    .PARAMETER Integrity
        If set, performs deeper integrity validation based on file extension:
        - .png : validates via System.Drawing.Bitmap
        - .sram/.srm/.sav: checks canonical MDRT / VLAB / READY offsets
        - visual_vdp_dump.bin: checks minimum size and non-uniformity
        - .bin: checks MinBytes
    .PARAMETER Kind
        Explicit artifact kind. Auto maps known extensions and rejects unknown
        extensions when -Integrity is used.
    .PARAMETER MinBytes
        Optional minimum byte count for binary checks.
    .OUTPUTS
        $true if file exists and passes checks, $false otherwise.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [switch]$Integrity,
        [ValidateSet('Auto', 'Png', 'Sram', 'VdpDump', 'Bin')]
        [string]$Kind = 'Auto',
        [int]$MinBytes = 0
    )

    if (-not (Test-Path -LiteralPath $FilePath)) { return $false }
    $info = Get-Item -LiteralPath $FilePath -ErrorAction SilentlyContinue
    if ($null -eq $info -or $info.Length -eq 0) { return $false }
    if ($MinBytes -gt 0 -and $info.Length -lt $MinBytes) { return $false }

    if (-not $Integrity) { return $true }

    $effectiveKind = $Kind
    $ext = [System.IO.Path]::GetExtension($FilePath).ToLowerInvariant()
    if ($effectiveKind -eq 'Auto') {
        $fileName = [System.IO.Path]::GetFileName($FilePath).ToLowerInvariant()
        switch ($ext) {
            '.png' { $effectiveKind = 'Png' }
            '.sram' { $effectiveKind = 'Sram' }
            '.srm' { $effectiveKind = 'Sram' }
            '.sav' { $effectiveKind = 'Sram' }
            '.bin' {
                if ($fileName -eq 'visual_vdp_dump.bin') {
                    $effectiveKind = 'VdpDump'
                } else {
                    $effectiveKind = 'Bin'
                }
            }
            default { return $false }
        }
    }

    switch ($effectiveKind) {
        'Png'     { return Test-SgdkPngIntegrity -FilePath $FilePath }
        'Sram'    { return Test-SgdkSramIntegrity -FilePath $FilePath }
        'VdpDump' { return Test-SgdkVdpDumpIntegrity -FilePath $FilePath -MinBytes ($(if ($MinBytes -gt 0) { $MinBytes } else { 16 })) }
        'Bin'     { return Test-SgdkBinIntegrity -FilePath $FilePath -MinBytes ($(if ($MinBytes -gt 0) { $MinBytes } else { 1 })) }
        default   { return $false }
    }
}

function Get-SgdkBinarySha256 {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$FilePath
    )

    $stream = [System.IO.File]::OpenRead($FilePath)
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha256.ComputeHash($stream)
        return ([System.BitConverter]::ToString($hashBytes).Replace('-', '')).ToLowerInvariant()
    } finally {
        $sha256.Dispose()
        $stream.Dispose()
    }
}

# ---------------------------------------------------------------------------
# Get-SgdkRomIdentity
# ---------------------------------------------------------------------------
function Get-SgdkRomIdentity {
    <#
    .SYNOPSIS
        Computes identity metadata for a ROM file.
    .PARAMETER RomPath
        Absolute path to the ROM file.
    .OUTPUTS
        Hashtable with rom_path, rom_sha256, rom_size_bytes.
        If ROM is missing, rom_sha256 is "MISSING" and rom_size_bytes is 0.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RomPath
    )

    $result = [ordered]@{
        rom_path       = $RomPath
        rom_sha256     = 'MISSING'
        rom_size_bytes = 0
    }

    if (Test-Path -LiteralPath $RomPath) {
        $result['rom_sha256'] = Get-SgdkBinarySha256 -FilePath $RomPath
        $result['rom_size_bytes'] = (Get-Item -LiteralPath $RomPath).Length
    }

    return $result
}

# ---------------------------------------------------------------------------
# Resolve-SgdkArtifactReportPath
# ---------------------------------------------------------------------------
function Resolve-SgdkArtifactReportPath {
    <#
    .SYNOPSIS
        Resolves the canonical report path for a given tool/script name.
    .PARAMETER ToolName
        Logical tool name used to derive the filename (e.g. "scene_closeout_gate").
    .PARAMETER ProjectRoot
        Absolute path to the project root.
    .PARAMETER ExplicitPath
        Optional explicit override. If provided, returned verbatim.
    .OUTPUTS
        Absolute path string to the .json report file.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ToolName,
        [Parameter(Mandatory)][string]$ProjectRoot,
        [string]$ExplicitPath
    )

    if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {
        return $ExplicitPath
    }

    $LogDir = Join-Path $ProjectRoot "out\logs"
    $safeName = $ToolName -replace '[^A-Za-z0-9_.-]', '_'
    return Join-Path $LogDir "${safeName}_report.json"
}

# ---------------------------------------------------------------------------
# Write-SgdkFallbackFailureArtifact
# ---------------------------------------------------------------------------
function Write-SgdkFallbackFailureArtifact {
    <#
    .SYNOPSIS
        Writes a minimal failure artifact to disk.
    .DESCRIPTION
        Designed for use in finally blocks to guarantee an artifact exists even
        after an unhandled exception. Uses the public Write-SgdkJsonArtifact so
        parent directory creation is handled automatically.
    .PARAMETER ReportPath
        Absolute path for the output JSON file.
    .PARAMETER ToolName
        Name of the generating tool.
    .PARAMETER ToolVersion
        Version of the generating tool.
    .PARAMETER ProjectRoot
        Absolute path to the project root.
    .PARAMETER FailureReason
        Human-readable failure description.
    .PARAMETER DomainData
        Optional extra data merged into the artifact (e.g. domain-specific status).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ReportPath,
        [Parameter(Mandatory)][string]$ToolName,
        [Parameter(Mandatory)][string]$ToolVersion,
        [Parameter(Mandatory)][string]$ProjectRoot,
        [Parameter(Mandatory)][string]$FailureReason,
        [System.Collections.IDictionary]$DomainData = $null
    )

    $fallback = New-SgdkArtifactEnvelope -ToolName $ToolName -ToolVersion $ToolVersion -ProjectRoot $ProjectRoot
    $fallback['status'] = 'error'
    $fallback['failure_reason'] = $FailureReason

    if ($DomainData -ne $null) {
        foreach ($key in $DomainData.Keys) { $fallback[$key] = $DomainData[$key] }
    }

    Write-SgdkJsonArtifact -Data $fallback -Path $ReportPath | Out-Null
    Write-Host ("[FALLBACK] wrote failure artifact to {0}: {1}" -f $ReportPath, $FailureReason)
}

# ---------------------------------------------------------------------------
# Extensions for Test-SgdkRequiredFile -Integrity
# ---------------------------------------------------------------------------
function Read-SgdkU16BE {
    param(
        [Parameter(Mandatory)][byte[]]$Bytes,
        [Parameter(Mandatory)][int]$Offset
    )

    return (([int]$Bytes[$Offset] -shl 8) -bor [int]$Bytes[$Offset + 1])
}

function Test-SgdkAsciiMagicAt {
    param(
        [Parameter(Mandatory)][byte[]]$Bytes,
        [Parameter(Mandatory)][int]$Offset,
        [Parameter(Mandatory)][string]$Magic
    )

    if ($Offset -lt 0 -or ($Offset + $Magic.Length) -gt $Bytes.Length) { return $false }
    return ([System.Text.Encoding]::ASCII.GetString($Bytes, $Offset, $Magic.Length) -eq $Magic)
}

function Test-SgdkMdrtBlockAt {
    param(
        [Parameter(Mandatory)][byte[]]$Bytes,
        [Parameter(Mandatory)][int]$Offset
    )

    if (-not (Test-SgdkAsciiMagicAt -Bytes $Bytes -Offset $Offset -Magic 'MDRT')) { return $false }
    if (($Offset + 10) -gt $Bytes.Length) { return $false }

    $schema = Read-SgdkU16BE -Bytes $Bytes -Offset ($Offset + 4)
    $totalBytes = Read-SgdkU16BE -Bytes $Bytes -Offset ($Offset + 6)
    $wordCount = Read-SgdkU16BE -Bytes $Bytes -Offset ($Offset + 8)

    if ($schema -lt 1) { return $false }
    if ($wordCount -lt 64 -or $wordCount -gt 8192) { return $false }

    $minimumBlockBytes = 10 + ($wordCount * 2)
    if ($totalBytes -lt $minimumBlockBytes) { return $false }
    if (($Offset + $totalBytes) -gt $Bytes.Length) { return $false }

    return $true
}

function Test-SgdkVlabBlockAt {
    param(
        [Parameter(Mandatory)][byte[]]$Bytes,
        [Parameter(Mandatory)][int]$Offset
    )

    if (-not (Test-SgdkAsciiMagicAt -Bytes $Bytes -Offset $Offset -Magic 'VLAB')) { return $false }
    if (($Offset + 8) -gt $Bytes.Length) { return $false }

    $totalBytes = Read-SgdkU16BE -Bytes $Bytes -Offset ($Offset + 6)
    if ($totalBytes -lt 8) { return $false }
    if (($Offset + $totalBytes) -gt $Bytes.Length) { return $false }

    return $true
}

function Test-SgdkPngIntegrity {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$FilePath)

    if (-not (Test-Path -LiteralPath $FilePath -PathType Leaf)) { return $false }
    try {
        $img = [System.Drawing.Bitmap]::FromFile($FilePath)
        $valid = ($null -ne $img)
        $img.Dispose()
        return $valid
    } catch {
        return $false
    }
}

function Test-SgdkSramIntegrity {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$FilePath)

    if (-not (Test-Path -LiteralPath $FilePath -PathType Leaf)) { return $false }
    try {
        $bytes = [System.IO.File]::ReadAllBytes($FilePath)
        if ($bytes.Length -lt 8) { return $false }

        if (Test-SgdkAsciiMagicAt -Bytes $bytes -Offset 0x100 -Magic 'READY') {
            return $true
        }

        foreach ($offset in @(0x200, 0x0)) {
            if (Test-SgdkMdrtBlockAt -Bytes $bytes -Offset $offset) { return $true }
        }

        foreach ($offset in @(0x0, 0x200, 0x400)) {
            if (Test-SgdkVlabBlockAt -Bytes $bytes -Offset $offset) { return $true }
        }

        return $false
    } catch {
        return $false
    }
}

function Test-SgdkVdpDumpIntegrity {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [int]$MinBytes = 16
    )

    if (-not (Test-Path -LiteralPath $FilePath -PathType Leaf)) { return $false }
    try {
        $info = Get-Item -LiteralPath $FilePath
        if ($info.Length -lt $MinBytes) { return $false }
        $bytes = [System.IO.File]::ReadAllBytes($FilePath)
        $headerOk = ($null -ne $bytes -and $bytes.Length -gt 0)
        $hasVariation = $false
        for ($i = 1; $i -lt [Math]::Min($bytes.Length, 256); $i++) {
            if ($bytes[$i] -ne $bytes[0]) { $hasVariation = $true; break }
        }
        return ($headerOk -and $hasVariation)
    } catch {
        return $false
    }
}

function Test-SgdkBinIntegrity {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [int]$MinBytes = 1
    )

    if (-not (Test-Path -LiteralPath $FilePath -PathType Leaf)) { return $false }
    try {
        $info = Get-Item -LiteralPath $FilePath
        return ($info.Length -ge $MinBytes)
    } catch {
        return $false
    }
}

# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------
Export-ModuleMember -Function @(
    'New-SgdkArtifactEnvelope',
    'Set-SgdkArtifactFailure',
    'Write-SgdkJsonArtifact',
    'Test-SgdkRequiredFile',
    'Get-SgdkBinarySha256',
    'Get-SgdkRomIdentity',
    'Resolve-SgdkArtifactReportPath',
    'Write-SgdkFallbackFailureArtifact',
    'Test-SgdkPngIntegrity',
    'Test-SgdkSramIntegrity',
    'Test-SgdkVdpDumpIntegrity',
    'Test-SgdkBinIntegrity'
)
