<#
.SYNOPSIS
    Common artifact envelope helpers for the AAA agent ecosystem.
.DESCRIPTION
    Provides standardized functions for creating, writing, and validating
    JSON artifacts generated by new tooling scripts. All artifacts share
    the common_artifact.schema.json envelope.
.NOTES
    This module does NOT modify any existing wrapper behavior.
    It is consumed only by new standalone scripts behind feature flags.
#>

Set-StrictMode -Version Latest

# ---------------------------------------------------------------------------
# New-SgdkArtifactEnvelope
# ---------------------------------------------------------------------------
function New-SgdkArtifactEnvelope {
    <#
    .SYNOPSIS
        Creates a new artifact envelope hashtable with mandatory base fields.
    .PARAMETER ToolName
        Name of the generating tool (e.g. "capture_blastem_evidence").
    .PARAMETER ToolVersion
        Semantic version of the generating tool.
    .PARAMETER ProjectRoot
        Absolute path to the project root directory.
    .PARAMETER WorkspaceRoot
        Absolute path to the MegaDrive_DEV workspace root.
        If omitted, attempts auto-discovery via MD_ROOT env var.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ToolName,
        [Parameter(Mandatory)][string]$ToolVersion,
        [Parameter(Mandatory)][string]$ProjectRoot,
        [string]$WorkspaceRoot
    )

    if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
        $WorkspaceRoot = $env:MD_ROOT
        if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
            # Fallback: walk up from script location looking for CLAUDE.md
            $probe = $PSScriptRoot
            for ($i = 0; $i -lt 5; $i++) {
                $probe = Split-Path $probe -Parent
                if (Test-Path (Join-Path $probe 'CLAUDE.md')) {
                    $WorkspaceRoot = $probe
                    break
                }
            }
        }
        if ([string]::IsNullOrWhiteSpace($WorkspaceRoot)) {
            $WorkspaceRoot = 'UNKNOWN'
        }
    }

    return [ordered]@{
        schema_version = '1.0.0'
        generated_at   = (Get-Date).ToUniversalTime().ToString('o')
        tool_name      = $ToolName
        tool_version   = $ToolVersion
        project_root   = $ProjectRoot
        workspace_root = $WorkspaceRoot
        status         = 'ok'
        failure_reason = $null
    }
}

# ---------------------------------------------------------------------------
# Set-SgdkArtifactFailure
# ---------------------------------------------------------------------------
function Set-SgdkArtifactFailure {
    <#
    .SYNOPSIS
        Marks an artifact envelope as failed with a reason.
    .PARAMETER Artifact
        The artifact hashtable (modified in-place).
    .PARAMETER Reason
        Human-readable failure description.
    .PARAMETER Warn
        If set, status becomes "warn" instead of "error".
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Artifact,
        [Parameter(Mandatory)][string]$Reason,
        [switch]$Warn
    )

    $Artifact['status'] = if ($Warn) { 'warn' } else { 'error' }
    $Artifact['failure_reason'] = $Reason
}

# ---------------------------------------------------------------------------
# Write-SgdkJsonArtifact
# ---------------------------------------------------------------------------
function Write-SgdkJsonArtifact {
    <#
    .SYNOPSIS
        Serializes an artifact hashtable to a JSON file with UTF-8 encoding.
    .PARAMETER Data
        The artifact hashtable to serialize.
    .PARAMETER Path
        Absolute path for the output JSON file.
        Parent directory is created automatically if missing.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Data,
        [Parameter(Mandatory)][string]$Path
    )

    $parentDir = Split-Path $Path -Parent
    if (-not (Test-Path -LiteralPath $parentDir)) {
        New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
    }

    $json = $Data | ConvertTo-Json -Depth 20
    [System.IO.File]::WriteAllText($Path, $json, [System.Text.Encoding]::UTF8)
    return $Path
}

# ---------------------------------------------------------------------------
# Test-SgdkRequiredFile
# ---------------------------------------------------------------------------
function Test-SgdkRequiredFile {
    <#
    .SYNOPSIS
        Checks whether a required file exists and is non-empty.
    .PARAMETER FilePath
        Absolute path to check.
    .OUTPUTS
        $true if file exists and has size > 0, $false otherwise.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$FilePath
    )

    if (-not (Test-Path -LiteralPath $FilePath)) { return $false }
    $info = Get-Item -LiteralPath $FilePath -ErrorAction SilentlyContinue
    return ($null -ne $info -and $info.Length -gt 0)
}

# ---------------------------------------------------------------------------
# Get-SgdkRomIdentity
# ---------------------------------------------------------------------------
function Get-SgdkRomIdentity {
    <#
    .SYNOPSIS
        Computes identity metadata for a ROM file.
    .PARAMETER RomPath
        Absolute path to the ROM file.
    .OUTPUTS
        Hashtable with rom_path, rom_sha256, rom_size_bytes.
        If ROM is missing, rom_sha256 is "MISSING" and rom_size_bytes is 0.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RomPath
    )

    $result = [ordered]@{
        rom_path       = $RomPath
        rom_sha256     = 'MISSING'
        rom_size_bytes = 0
    }

    if (Test-Path -LiteralPath $RomPath) {
        $hash = Get-FileHash -LiteralPath $RomPath -Algorithm SHA256
        $result['rom_sha256'] = $hash.Hash.ToLower()
        $result['rom_size_bytes'] = (Get-Item -LiteralPath $RomPath).Length
    }

    return $result
}

# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------
Export-ModuleMember -Function @(
    'New-SgdkArtifactEnvelope',
    'Set-SgdkArtifactFailure',
    'Write-SgdkJsonArtifact',
    'Test-SgdkRequiredFile',
    'Get-SgdkRomIdentity'
)
